# Exported from Render on 2026-06-26T12:26:19Z
version: "1"
projects:
- name: url-shortner-api
  environments:
  - name: Production
    services:
    - type: web
      name: url-shortener-api
      runtime: docker
      repo: https://github.com/PratikDev/url-shortener-api
      plan: free
      envVars:
      - key: POSTGRES_PASSWORD
        sync: false
      - key: POSTGRES_HOST
        sync: false
      - key: POSTGRES_DB
        sync: false
      - key: PORT
        sync: false
      - key: BASE_URL
        sync: false
      - key: POSTGRES_PORT
        sync: false
      - key: POSTGRES_USER
        sync: false
      region: oregon
      healthCheckPath: /health
      dockerContext: .
      dockerfilePath: ./Dockerfile
      autoDeployTrigger: commit
